@startuml
'https://plantuml.com/class-diagram

class App{
    main()
    start()
}

class ToDoListController{
    listDisplay: ListField
    todolist list: List<ToDoList>

    SaveListButtonClicked()
    SaveAllListButtonClicked()
    LoadListButtonClicked()
    LoadAllListButtonClicked()
    addListButtonClicked()
    removeListButtonClicked()
    editListButtonClicked()
    DisplayItemsButtonClicked()
    DisplayIncompleteItemsButtonClicked()
    DisplayCompleteItemsButtonClicked()
    SaveList()
    SaveAllList()
    LoadList()
    LoadAllList()
    addList()
    removeList()
    editList()
    DisplayItems()
    DisplayIncompleteItems()
    DisplayCompleteItems()
}

class ItemController{
    listDisplay: ItemField
    addItemButtonClicked()
    removeItemButtonClicked()
    editItemDescriptionButtonClicked()
    editItemDueDateButtonClicked()
    markItemCompleteButtonClicked()
    addItem()
    removeItem()
    editItemDescription()
    editItemDueDate()
    markItemComplete()
}

class ToDoList{
    Title: String
    ItemList: List<Items>
    updateTitle()
}

class Item{
    Description: String
    DueDate: int 'YYYY-MM-DD'
    Completion: Boolean
    updateDescription()
    updateDueDate()
    updateCompletion()
}

Item <-* ItemController
ToDoListController *-> ToDoList
App *--> ToDoListController
ToDoList *--> ItemController

@enduml